version: "3.8"

services:
  p_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1323:1323"
    environment:
      - DB_HOST=p_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=amartyadavnainital15!
      - DB_NAME=panchangapi
    depends_on:
      p_db:
        condition: service_healthy
  p_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=amartyadavnainital15!
      - POSTGRES_DB=panchangapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
